# DVC Pipeline Configuration
# To run the pipeline: dvc repro
# To run experiments: dvc exp run
# To run with param override: dvc exp run --set-param train_models.n_trials=100
# To visualize: dvc dag

stages:
  # Stage 1: Convert raw data to intermediate format
  bronze_to_silver:
    cmd: uv run python -m src.pipelines.data.bronze_to_silver
    deps:
      - src/pipelines/data/bronze_to_silver.py
      # - data/bronze/  # Add your bronze data dependencies here
    # outs:
    #   - data/silver/  # Add your silver data outputs here

  # Stage 2: Convert silver data to gold format
  silver_to_gold:
    cmd: uv run python -m src.pipelines.data.silver_to_gold
    deps:
      - src/pipelines/data/silver_to_gold.py
      # - data/silver/  # Add your silver data dependencies here
    # outs:
    #   - data/gold/  # Add your gold data outputs here

  # Stage 3: Train taxi time prediction models
  train_models:
    cmd: uv run python -m src.pipelines.models.train_models
    deps:
      - src/pipelines/models/train_models.py
      - src/pipelines/models/linear_regression.py
      - src/pipelines/utils/model_inputs_loading.py
      # - data/gold/  # Add your gold data dependencies here
    params:
      - train_models
      - hyperparameters
