# DVC Parameters Configuration
# Modify these values and run `dvc exp run` to experiment with different settings
# Or use `dvc exp run --set-param train_models.n_trials=100` to override

train_models:
  model_types:
    - linear_regression
    - xgboost
    - random_forest
    - lightgbm
    - catboost

hyperparameters:
  linear_regression:
    fit_intercept: [true, false]
  xgboost: null  # Uses default search space in xgboost_model.py
  random_forest: null  # Uses default search space in random_forest.py
  lightgbm: null  # Uses default search space in lightgbm_model.py
  catboost: null  # Uses default search space in catboost_model.py
